import type { Linter } from "eslint";

import vitestPlugin from "@vitest/eslint-plugin";

import { TYPESCRIPT_TEST_FILES } from "../constants/index.js";

const vitestRules: Linter.RulesRecord = {
  "vitest/consistent-each-for": "off",
  "vitest/consistent-test-filename": "off",
  "vitest/consistent-test-it": [
    "error",
    { fn: "it", withinDescribe: "it" },
  ],
  "vitest/consistent-vitest-vi": ["error", { fn: "vi" }],
  "vitest/expect-expect": "error",
  "vitest/hoisted-apis-on-top": "error",
  "vitest/max-expects": "off",
  "vitest/max-nested-describe": "off",
  "vitest/no-alias-methods": "error",
  "vitest/no-commented-out-tests": "error",
  "vitest/no-conditional-expect": "error",
  "vitest/no-conditional-in-test": "error",
  "vitest/no-conditional-tests": "error",
  "vitest/no-disabled-tests": "error",
  "vitest/no-done-callback": "error",
  "vitest/no-duplicate-hooks": "error",
  "vitest/no-focused-tests": "error",
  "vitest/no-hooks": "off",
  "vitest/no-identical-title": "error",
  "vitest/no-import-node-test": "error",
  "vitest/no-importing-vitest-globals": "off",
  "vitest/no-interpolation-in-snapshots": "error",
  "vitest/no-large-snapshots": "off",
  "vitest/no-mocks-import": "error",
  "vitest/no-restricted-matchers": "off",
  "vitest/no-restricted-vi-methods": "off",
  "vitest/no-standalone-expect": "error",
  "vitest/no-test-prefixes": "error",
  "vitest/no-test-return-statement": "error",
  "vitest/no-unneeded-async-expect-function": "error",
  "vitest/padding-around-after-all-blocks": "error",
  "vitest/padding-around-after-each-blocks": "error",
  "vitest/padding-around-all": "off",
  "vitest/padding-around-before-all-blocks": "error",
  "vitest/padding-around-before-each-blocks": "error",
  "vitest/padding-around-describe-blocks": "error",
  "vitest/padding-around-expect-groups": "off",
  "vitest/padding-around-test-blocks": "error",
  "vitest/prefer-called-exactly-once-with": "error",
  "vitest/prefer-called-once": "off",
  "vitest/prefer-called-times": "off",
  "vitest/prefer-called-with": "error",
  "vitest/prefer-comparison-matcher": "error",
  "vitest/prefer-describe-function-title": "off",
  "vitest/prefer-each": "error",
  "vitest/prefer-equality-matcher": "error",
  "vitest/prefer-expect-assertions": "off",
  "vitest/prefer-expect-resolves": "error",
  "vitest/prefer-expect-type-of": "error",
  "vitest/prefer-hooks-in-order": "error",
  "vitest/prefer-hooks-on-top": "error",
  "vitest/prefer-import-in-mock": "error",
  "vitest/prefer-importing-vitest-globals": "off",
  "vitest/prefer-lowercase-title": [
    "error",
    { ignore: ["describe"] },
  ],
  "vitest/prefer-mock-promise-shorthand": "error",
  "vitest/prefer-mock-return-shorthand": "error",
  "vitest/prefer-snapshot-hint": "off",
  "vitest/prefer-spy-on": "error",
  "vitest/prefer-strict-boolean-matchers": "error",
  "vitest/prefer-strict-equal": "off",
  "vitest/prefer-to-be": "error",
  "vitest/prefer-to-be-falsy": "off",
  "vitest/prefer-to-be-object": "error",
  "vitest/prefer-to-be-truthy": "off",
  "vitest/prefer-to-contain": "error",
  "vitest/prefer-to-have-been-called-times": "error",
  "vitest/prefer-to-have-length": "error",
  "vitest/prefer-todo": "error",
  "vitest/prefer-vi-mocked": "error",
  "vitest/require-awaited-expect-poll": "error",
  "vitest/require-hook": "error",
  "vitest/require-local-test-context-for-concurrent-snapshots": "error",
  "vitest/require-mock-type-parameters": "off",
  "vitest/require-test-timeout": "off",
  "vitest/require-to-throw-message": "off",
  "vitest/require-top-level-describe": "error",
  "vitest/unbound-method": "off",
  "vitest/valid-describe-callback": "error",
  "vitest/valid-expect": ["error", { maxArgs: 2 }],
  "vitest/valid-expect-in-promise": "error",
  "vitest/valid-title": "error",
  "vitest/warn-todo": "off",
};

export const vitest: Linter.Config[] = [
  {
    files: TYPESCRIPT_TEST_FILES,
    name: "yarapa/vitest",
    plugins: {
      vitest: vitestPlugin as unknown as NonNullable<
        Linter.Config["plugins"]
      >[string],
    },
    rules: vitestRules,
  },
];
