import type { Linter } from "eslint";

import sonarjsPlugin from "eslint-plugin-sonarjs";

import { JAVASCRIPT_AND_TYPESCRIPT_FILES } from "../constants/index.js";

const sonarjsRules: Linter.RulesRecord = {
  "sonarjs/argument-type": "error",
  "sonarjs/arguments-order": "error",
  "sonarjs/arguments-usage": "off",
  "sonarjs/array-callback-without-return": "error",
  "sonarjs/array-constructor": "off",
  "sonarjs/arrow-function-convention": "off",
  "sonarjs/aws-apigateway-public-api": "error",
  "sonarjs/aws-ec2-rds-dms-public": "error",
  "sonarjs/aws-ec2-unencrypted-ebs-volume": "error",
  "sonarjs/aws-efs-unencrypted": "error",
  "sonarjs/aws-iam-all-privileges": "error",
  "sonarjs/aws-iam-all-resources-accessible": "off",
  "sonarjs/aws-iam-privilege-escalation": "error",
  "sonarjs/aws-iam-public-access": "error",
  "sonarjs/aws-opensearchservice-domain": "error",
  "sonarjs/aws-rds-unencrypted-databases": "error",
  "sonarjs/aws-restricted-ip-admin-access": "error",
  "sonarjs/aws-s3-bucket-granted-access": "error",
  "sonarjs/aws-s3-bucket-insecure-http": "error",
  "sonarjs/aws-s3-bucket-public-access": "error",
  "sonarjs/aws-s3-bucket-versioning": "error",
  "sonarjs/aws-sagemaker-unencrypted-notebook": "error",
  "sonarjs/aws-sns-unencrypted-topics": "error",
  "sonarjs/aws-sqs-unencrypted-queue": "error",
  "sonarjs/bitwise-operators": "error",
  "sonarjs/block-scoped-var": "error",
  "sonarjs/bool-param-default": "off",
  "sonarjs/call-argument-line": "error",
  "sonarjs/class-name": [
    "error",
    { format: String.raw`^\$?[A-Z][a-zA-Z0-9]*$` },
  ],
  "sonarjs/class-prototype": "off",
  "sonarjs/code-eval": "error",
  "sonarjs/cognitive-complexity": ["error", 15],
  "sonarjs/comma-or-logical-or-case": "error",
  "sonarjs/comment-regex": [
    "off",
    {
      flags: "",
      message: "The regular expression matches this comment.",
      regularExpression: "",
    },
  ],
  "sonarjs/conditional-indentation": "off",
  "sonarjs/confidential-information-logging": "off",
  "sonarjs/constructor-for-side-effects": "error",
  "sonarjs/content-length": [
    "error",
    { fileUploadSizeLimit: 8_000_000, standardSizeLimit: 2_000_000 },
  ],
  "sonarjs/content-security-policy": "error",
  "sonarjs/cookie-no-httponly": "error",
  "sonarjs/cors": "error",
  "sonarjs/csrf": "error",
  "sonarjs/cyclomatic-complexity": ["off", { threshold: 10 }],
  "sonarjs/declarations-in-global-scope": "off",
  "sonarjs/deprecation": "error",
  "sonarjs/destructuring-assignment-syntax": "off",
  "sonarjs/different-types-comparison": "error",
  "sonarjs/disabled-auto-escaping": "error",
  "sonarjs/disabled-resource-integrity": "error",
  "sonarjs/disabled-timeout": "error",
  "sonarjs/dompurify-unsafe-config": "error",
  "sonarjs/dynamically-constructed-templates": "error",
  "sonarjs/elseif-without-else": "off",
  "sonarjs/encryption-secure-mode": "error",
  "sonarjs/expression-complexity": ["off", { max: 3 }],
  "sonarjs/file-header": [
    "off",
    { headerFormat: "", isRegularExpression: false },
  ],
  "sonarjs/file-name-differ-from-class": "off",
  "sonarjs/file-permissions": "error",
  "sonarjs/file-uploads": "error",
  "sonarjs/fixme-tag": "error",
  "sonarjs/for-in": "off",
  "sonarjs/frame-ancestors": "off",
  "sonarjs/function-inside-loop": "error",
  "sonarjs/function-name": ["off", { format: "^[_a-z][a-zA-Z0-9]*$" }],
  "sonarjs/function-return-type": "error",
  "sonarjs/future-reserved-words": "error",
  "sonarjs/hardcoded-secret-signatures": "error",
  "sonarjs/hashing": "error",
  "sonarjs/hidden-files": "off",
  "sonarjs/in-operator-type-error": "error",
  "sonarjs/inconsistent-function-call": "error",
  "sonarjs/index-of-compare-to-positive-number": "error",
  "sonarjs/insecure-cookie": "error",
  "sonarjs/insecure-jwt-token": "error",
  "sonarjs/jsx-no-leaked-render": "error",
  "sonarjs/label-position": "error",
  "sonarjs/link-with-target-blank": "error",
  "sonarjs/max-lines": ["off", { maximum: 1000 }],
  "sonarjs/max-lines-per-function": ["off", { maximum: 200 }],
  "sonarjs/max-switch-cases": ["error", 30],
  "sonarjs/max-union-size": ["off", { threshold: 3 }],
  "sonarjs/memoize-cache-key": "error",
  "sonarjs/misplaced-loop-counter": "error",
  "sonarjs/nested-control-flow": ["off", { maximumNestingLevel: 3 }],
  "sonarjs/no-all-duplicated-branches": "error",
  "sonarjs/no-alphabetical-sort": "error",
  "sonarjs/no-angular-bypass-sanitization": "error",
  "sonarjs/no-associative-arrays": "error",
  "sonarjs/no-async-constructor": "error",
  "sonarjs/no-built-in-override": "off",
  "sonarjs/no-clear-text-protocols": "error",
  "sonarjs/no-collapsible-if": "off",
  "sonarjs/no-collection-size-mischeck": "error",
  "sonarjs/no-commented-code": "off",
  "sonarjs/no-dead-store": "error",
  "sonarjs/no-debug-commands-in-ui-tests": "error",
  "sonarjs/no-default-utility-imports": "error",
  "sonarjs/no-duplicate-string": [
    "off",
    { ignoreStrings: "application/json", threshold: 3 },
  ],
  "sonarjs/no-duplicated-branches": "error",
  "sonarjs/no-element-overwrite": "error",
  "sonarjs/no-empty-collection": "error",
  "sonarjs/no-equals-in-for-termination": "error",
  "sonarjs/no-extra-arguments": "error",
  "sonarjs/no-fixed-wait-in-tests": "error",
  "sonarjs/no-floating-point-equality": "error",
  "sonarjs/no-for-in-iterable": "off",
  "sonarjs/no-forced-browser-interaction": "error",
  "sonarjs/no-function-declaration-in-block": "off",
  "sonarjs/no-gratuitous-expressions": "error",
  "sonarjs/no-hardcoded-ip": "error",
  "sonarjs/no-hardcoded-passwords": [
    "error",
    { passwordWords: ["password", "pwd", "passwd", "passphrase"] },
  ],
  "sonarjs/no-hardcoded-secrets": [
    "error",
    {
      randomnessSensibility: 5,
      secretWords: "api[_.-]?key,auth,credential,secret,token",
    },
  ],
  "sonarjs/no-hook-setter-in-body": "error",
  "sonarjs/no-identical-expressions": "error",
  "sonarjs/no-identical-functions": ["error", 3],
  "sonarjs/no-ignored-exceptions": "error",
  "sonarjs/no-ignored-return": "error",
  "sonarjs/no-implicit-dependencies": ["off", { whitelist: [] }],
  "sonarjs/no-implicit-global": "error",
  "sonarjs/no-in-misuse": "error",
  "sonarjs/no-inconsistent-returns": "off",
  "sonarjs/no-incorrect-string-concat": "off",
  "sonarjs/no-internal-api-use": "error",
  "sonarjs/no-intrusive-permissions": ["off", { permissions: ["geolocation"] }],
  "sonarjs/no-invariant-returns": "error",
  "sonarjs/no-inverted-boolean-check": "error",
  "sonarjs/no-ip-forward": "off",
  "sonarjs/no-labels": "error",
  "sonarjs/no-literal-call": "error",
  "sonarjs/no-mime-sniff": "error",
  "sonarjs/no-mixed-completion-style": "error",
  "sonarjs/no-mixed-content": "off",
  "sonarjs/no-nested-functions": ["error", { threshold: 4 }],
  "sonarjs/no-nested-incdec": "off",
  "sonarjs/no-nested-switch": "off",
  "sonarjs/no-nested-template-literals": "error",
  "sonarjs/no-os-command-from-path": "error",
  "sonarjs/no-parameter-reassignment": "error",
  "sonarjs/no-redundant-assignments": "error",
  "sonarjs/no-redundant-boolean": "error",
  "sonarjs/no-redundant-jump": "error",
  "sonarjs/no-redundant-optional": "error",
  "sonarjs/no-redundant-parentheses": "off",
  "sonarjs/no-reference-error": "off",
  "sonarjs/no-referrer-policy": "error",
  "sonarjs/no-require-or-define": "off",
  "sonarjs/no-return-type-any": "off",
  "sonarjs/no-same-line-conditional": "error",
  "sonarjs/no-selector-parameter": "error",
  "sonarjs/no-session-cookies-on-static-assets": "error",
  "sonarjs/no-small-switch": "error",
  "sonarjs/no-sonar-comments": "off",
  "sonarjs/no-tab": "off",
  "sonarjs/no-table-as-layout": "error",
  "sonarjs/no-try-promise": "error",
  "sonarjs/no-undefined-argument": "error",
  "sonarjs/no-undefined-assignment": "off",
  "sonarjs/no-unenclosed-multiline-block": "error",
  "sonarjs/no-uniq-key": "error",
  "sonarjs/no-unsafe-unzip": "off",
  "sonarjs/no-unthrown-error": "error",
  "sonarjs/no-unused-collection": "error",
  "sonarjs/no-use-of-empty-return-value": "error",
  "sonarjs/no-useless-increment": "error",
  "sonarjs/no-useless-intersection": "error",
  "sonarjs/no-useless-react-setstate": "error",
  "sonarjs/no-variable-usage-before-declaration": "off",
  "sonarjs/no-weak-cipher": "error",
  "sonarjs/no-weak-keys": "error",
  "sonarjs/no-wildcard-import": "off",
  "sonarjs/non-existent-operator": "error",
  "sonarjs/non-number-in-arithmetic-expression": "off",
  "sonarjs/null-dereference": "error",
  "sonarjs/object-alt-content": "error",
  "sonarjs/operation-returning-nan": "off",
  "sonarjs/os-command": "off",
  "sonarjs/post-message": "error",
  "sonarjs/prefer-default-last": "off",
  "sonarjs/prefer-immediate-return": "off",
  "sonarjs/prefer-native-lodash-alternative": "error",
  "sonarjs/prefer-object-literal": "off",
  "sonarjs/prefer-promise-shorthand": "error",
  "sonarjs/prefer-read-only-props": "error",
  "sonarjs/prefer-single-boolean-return": "error",
  "sonarjs/prefer-type-guard": "error",
  "sonarjs/prefer-while": "error",
  "sonarjs/production-debug": "error",
  "sonarjs/pseudo-random": "error",
  "sonarjs/public-static-readonly": "error",
  "sonarjs/publicly-writable-directories": "error",
  "sonarjs/review-blockchain-mnemonic": "error",
  "sonarjs/session-regeneration": "error",
  "sonarjs/shorthand-property-grouping": "off",
  "sonarjs/sql-queries": "error",
  "sonarjs/stable-tests": "error",
  "sonarjs/strict-transport-security": "error",
  "sonarjs/strings-comparison": "off",
  "sonarjs/table-header": "error",
  "sonarjs/table-header-reference": "error",
  "sonarjs/todo-tag": "error",
  "sonarjs/too-many-break-or-continue-in-loop": "off",
  "sonarjs/unverified-certificate": "error",
  "sonarjs/unverified-hostname": "error",
  "sonarjs/updated-loop-counter": "error",
  "sonarjs/use-type-alias": "error",
  "sonarjs/useless-string-operation": "off",
  "sonarjs/values-not-convertible-to-numbers": "off",
  "sonarjs/variable-name": [
    "off",
    { format: "^[_$A-Za-z][$A-Za-z0-9]*$|^[_$A-Z][_$A-Z0-9]+$" },
  ],
  "sonarjs/void-use": "error",
  "sonarjs/weak-ssl": "error",
  "sonarjs/web-sql-database": "off",
  "sonarjs/x-powered-by": "error",
  "sonarjs/xml-parser-xxe": "error",
};

export const sonarjs: Linter.Config[] = [
  {
    files: JAVASCRIPT_AND_TYPESCRIPT_FILES,
    name: "yarapa/sonarjs",
    plugins: { sonarjs: sonarjsPlugin },
    rules: sonarjsRules,
  },
];
