import type { Linter } from "eslint";

import jsdocPlugin from "eslint-plugin-jsdoc";

const jsdocJavaScriptRules: Linter.RulesRecord = {
  "jsdoc/check-access": "error",
  "jsdoc/check-alignment": "error",
  "jsdoc/check-examples": "off",
  "jsdoc/check-indentation": "off",
  "jsdoc/check-line-alignment": "off",
  "jsdoc/check-param-names": "error",
  "jsdoc/check-property-names": "error",
  "jsdoc/check-syntax": "off",
  "jsdoc/check-tag-names": "error",
  "jsdoc/check-template-names": "off",
  "jsdoc/check-types": "error",
  "jsdoc/check-values": "error",
  "jsdoc/convert-to-jsdoc-comments": "off",
  "jsdoc/empty-tags": "error",
  "jsdoc/escape-inline-tags": "error",
  "jsdoc/implements-on-classes": "error",
  "jsdoc/imports-as-dependencies": "off",
  "jsdoc/informative-docs": "off",
  "jsdoc/lines-before-block": "off",
  "jsdoc/match-description": "off",
  "jsdoc/match-name": "off",
  "jsdoc/multiline-blocks": "error",
  "jsdoc/no-bad-blocks": "off",
  "jsdoc/no-blank-block-descriptions": "off",
  "jsdoc/no-blank-blocks": "off",
  "jsdoc/no-defaults": "error",
  "jsdoc/no-missing-syntax": "off",
  "jsdoc/no-multi-asterisks": "error",
  "jsdoc/no-restricted-syntax": "off",
  "jsdoc/no-types": "off",
  "jsdoc/no-undefined-types": "error",
  "jsdoc/no-unnecessary-type-assertion": "off",
  "jsdoc/normalize-see-links": "off",
  "jsdoc/prefer-import-tag": "off",
  "jsdoc/reject-any-type": "error",
  "jsdoc/reject-function-type": "error",
  "jsdoc/require-asterisk-prefix": "off",
  "jsdoc/require-description": "off",
  "jsdoc/require-description-complete-sentence": "off",
  "jsdoc/require-example": "off",
  "jsdoc/require-file-overview": "off",
  "jsdoc/require-hyphen-before-param-description": "off",
  "jsdoc/require-jsdoc": "error",
  "jsdoc/require-next-description": "off",
  "jsdoc/require-next-type": "error",
  "jsdoc/require-param": "error",
  "jsdoc/require-param-description": "error",
  "jsdoc/require-param-name": "error",
  "jsdoc/require-param-type": "error",
  "jsdoc/require-property": "error",
  "jsdoc/require-property-description": "error",
  "jsdoc/require-property-name": "error",
  "jsdoc/require-property-type": "error",
  "jsdoc/require-rejects": "off",
  "jsdoc/require-returns": "error",
  "jsdoc/require-returns-check": "error",
  "jsdoc/require-returns-description": "error",
  "jsdoc/require-returns-type": "error",
  "jsdoc/require-tags": "off",
  "jsdoc/require-template": "off",
  "jsdoc/require-template-description": "off",
  "jsdoc/require-throws": "off",
  "jsdoc/require-throws-description": "off",
  "jsdoc/require-throws-type": "error",
  "jsdoc/require-yields": "error",
  "jsdoc/require-yields-check": "error",
  "jsdoc/require-yields-description": "off",
  "jsdoc/require-yields-type": "error",
  "jsdoc/sort-tags": "off",
  "jsdoc/tag-lines": "error",
  "jsdoc/text-escaping": "off",
  "jsdoc/ts-method-signature-style": "off",
  "jsdoc/ts-no-empty-object-type": "error",
  "jsdoc/ts-no-unnecessary-template-expression": "off",
  "jsdoc/ts-prefer-function-type": "off",
  "jsdoc/type-formatting": "off",
  "jsdoc/valid-types": "error",
};

const jsdocTypeScriptRules: Linter.RulesRecord = {
  "jsdoc/check-access": "error",
  "jsdoc/check-alignment": "error",
  "jsdoc/check-examples": "off",
  "jsdoc/check-indentation": "off",
  "jsdoc/check-line-alignment": "off",
  "jsdoc/check-param-names": "error",
  "jsdoc/check-property-names": "error",
  "jsdoc/check-syntax": "off",
  "jsdoc/check-tag-names": ["error", { typed: true }],
  "jsdoc/check-template-names": "off",
  "jsdoc/check-types": "error",
  "jsdoc/check-values": "error",
  "jsdoc/convert-to-jsdoc-comments": "off",
  "jsdoc/empty-tags": "error",
  "jsdoc/escape-inline-tags": "error",
  "jsdoc/implements-on-classes": "error",
  "jsdoc/imports-as-dependencies": "off",
  "jsdoc/informative-docs": "off",
  "jsdoc/lines-before-block": "off",
  "jsdoc/match-description": "off",
  "jsdoc/match-name": "off",
  "jsdoc/multiline-blocks": "error",
  "jsdoc/no-bad-blocks": "off",
  "jsdoc/no-blank-block-descriptions": "off",
  "jsdoc/no-blank-blocks": "off",
  "jsdoc/no-defaults": "error",
  "jsdoc/no-missing-syntax": "off",
  "jsdoc/no-multi-asterisks": "error",
  "jsdoc/no-restricted-syntax": "off",
  "jsdoc/no-types": "error",
  "jsdoc/no-undefined-types": "off",
  "jsdoc/no-unnecessary-type-assertion": "off",
  "jsdoc/normalize-see-links": "off",
  "jsdoc/prefer-import-tag": "off",
  "jsdoc/reject-any-type": "error",
  "jsdoc/reject-function-type": "error",
  "jsdoc/require-asterisk-prefix": "off",
  "jsdoc/require-description": "off",
  "jsdoc/require-description-complete-sentence": "off",
  "jsdoc/require-example": "off",
  "jsdoc/require-file-overview": "off",
  "jsdoc/require-hyphen-before-param-description": "off",
  "jsdoc/require-jsdoc": "error",
  "jsdoc/require-next-description": "off",
  "jsdoc/require-next-type": "error",
  "jsdoc/require-param": "error",
  "jsdoc/require-param-description": "error",
  "jsdoc/require-param-name": "error",
  "jsdoc/require-param-type": "off",
  "jsdoc/require-property": "error",
  "jsdoc/require-property-description": "error",
  "jsdoc/require-property-name": "error",
  "jsdoc/require-property-type": "off",
  "jsdoc/require-rejects": "off",
  "jsdoc/require-returns": "error",
  "jsdoc/require-returns-check": "error",
  "jsdoc/require-returns-description": "error",
  "jsdoc/require-returns-type": "off",
  "jsdoc/require-tags": "off",
  "jsdoc/require-template": "off",
  "jsdoc/require-template-description": "off",
  "jsdoc/require-throws": "off",
  "jsdoc/require-throws-description": "off",
  "jsdoc/require-throws-type": "error",
  "jsdoc/require-yields": "error",
  "jsdoc/require-yields-check": "error",
  "jsdoc/require-yields-description": "off",
  "jsdoc/require-yields-type": "error",
  "jsdoc/sort-tags": "off",
  "jsdoc/tag-lines": "error",
  "jsdoc/text-escaping": "off",
  "jsdoc/ts-method-signature-style": "off",
  "jsdoc/ts-no-empty-object-type": "error",
  "jsdoc/ts-no-unnecessary-template-expression": "off",
  "jsdoc/ts-prefer-function-type": "off",
  "jsdoc/type-formatting": "off",
  "jsdoc/valid-types": "error",
};

export const jsdoc: Linter.Config[] = [
  {
    files: ["**/*.js", "**/*.mjs", "**/*.cjs", "**/*.jsx"],
    name: "yarapa/jsdoc/javascript",
    plugins: { jsdoc: jsdocPlugin },
    rules: jsdocJavaScriptRules,
  },
  {
    files: ["**/*.ts", "**/*.mts", "**/*.cts", "**/*.tsx"],
    name: "yarapa/jsdoc/typescript",
    plugins: { jsdoc: jsdocPlugin },
    rules: jsdocTypeScriptRules,
  },
];
