import type { Linter } from "eslint";

import { JAVASCRIPT_AND_TYPESCRIPT_FILES } from "../constants/index.js";
import { ES_TOOLKIT_ALTERNATIVE_MESSAGE } from "./base.constant.js";

const coreRules: Linter.RulesRecord = {
  "constructor-super": "error",
  "for-direction": "error",
  "getter-return": "error",
  "no-async-promise-executor": "error",
  "no-case-declarations": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": "error",
  "no-const-assign": "error",
  "no-constant-binary-expression": "error",
  "no-constant-condition": "error",
  "no-control-regex": "error",
  "no-debugger": "error",
  "no-delete-var": "error",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-empty-static-block": "error",
  "no-ex-assign": "error",
  "no-extra-boolean-cast": "error",
  "no-fallthrough": "error",
  "no-func-assign": "error",
  "no-global-assign": "error",
  "no-import-assign": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-loss-of-precision": "error",
  "no-misleading-character-class": "error",
  "no-new-native-nonconstructor": "error",
  "no-nonoctal-decimal-escape": "error",
  "no-obj-calls": "error",
  "no-octal": "error",
  "no-prototype-builtins": "error",
  "no-redeclare": "error",
  "no-regex-spaces": "error",
  "no-self-assign": "error",
  "no-setter-return": "error",
  "no-shadow-restricted-names": "error",
  "no-sparse-arrays": "error",
  "no-this-before-super": "error",
  "no-unassigned-vars": "error",
  "no-undef": "error",
  "no-unexpected-multiline": "error",
  "no-unreachable": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unsafe-optional-chaining": "error",
  "no-unused-labels": "error",
  "no-unused-private-class-members": "error",
  "no-unused-vars": "error",
  "no-useless-assignment": "error",
  "no-useless-backreference": "error",
  "no-useless-catch": "error",
  "no-useless-escape": "error",
  "no-with": "error",
  "preserve-caught-error": "error",
  "require-yield": "error",
  "use-isnan": "error",
  "valid-typeof": "error",
};

const modernJavaScriptRules: Linter.RulesRecord = {
  "arrow-body-style": [
    "error",
    "as-needed",
    { requireReturnForObjectLiteral: false },
  ],
  curly: ["error", "all"],
  "default-param-last": "error",
  "dot-notation": "error",
  eqeqeq: ["error", "always"],
  "max-lines": [
    "error",
    { max: 300, skipBlankLines: true, skipComments: true },
  ],
  "no-array-constructor": "error",
  "no-inline-comments": "error",
  "no-object-constructor": "error",
  "no-restricted-imports": [
    "error",
    {
      paths: [
        {
          message: ES_TOOLKIT_ALTERNATIVE_MESSAGE,
          name: "lodash",
        },
        {
          message: ES_TOOLKIT_ALTERNATIVE_MESSAGE,
          name: "lodash-es",
        },
        {
          message: ES_TOOLKIT_ALTERNATIVE_MESSAGE,
          name: "underscore",
        },
        { message: ES_TOOLKIT_ALTERNATIVE_MESSAGE, name: "ramda" },
      ],
      patterns: [
        {
          group: ["lodash/*", "lodash-es/*"],
          message: ES_TOOLKIT_ALTERNATIVE_MESSAGE,
        },
        {
          group: ["underscore/*"],
          message: ES_TOOLKIT_ALTERNATIVE_MESSAGE,
        },
        {
          group: ["ramda/*"],
          message: ES_TOOLKIT_ALTERNATIVE_MESSAGE,
        },
      ],
    },
  ],
  "no-var": "error",
  "no-warning-comments": [
    "error",
    { location: "anywhere", terms: ["todo", "fixme", "xxx"] },
  ],
  "object-shorthand": ["error", "always"],
  "prefer-const": "error",
  "prefer-object-has-own": "error",
  "prefer-object-spread": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  radix: "error",
};

export const base: Linter.Config[] = [
  {
    linterOptions: {
      noInlineConfig: true,
      reportUnusedDisableDirectives: "error",
    },
    name: "yarapa/base/linter-options",
  },
  {
    files: JAVASCRIPT_AND_TYPESCRIPT_FILES,
    name: "yarapa/base/core",
    rules: coreRules,
  },
  {
    files: JAVASCRIPT_AND_TYPESCRIPT_FILES,
    name: "yarapa/base/modern-js",
    rules: modernJavaScriptRules,
  },
];
